M48
; DRILL file {KiCad 8.0.7} date 2025-01-23T23:10:58+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-01-23T23:10:58+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X5.1844Y-4.3858
X5.412Y-4.3858
T2
X4.8307Y-4.4764
X6.5157Y-4.4764
M30
