M48
; DRILL file {KiCad 8.0.7} date 2024-12-28T12:59:27+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-12-28T12:59:27+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X2.4549Y-1.648
X2.4549Y-1.8756
T2
X3.0866Y-1.5591
M30
