name: Publish Firmware

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-firmware:
    name: Build Firmware
    uses: esphome/workflows/.github/workflows/build.yml@2025.1.0
    with:
      files: |
        esphome/inkli.yaml
      esphome-version: latest

      release-summary: ${{ github.event.release.body }}
      release-url: ${{ github.event.release.html_url }}
      release-version: ${{ github.event.release.tag_name }}

  upload-to-release:
    name: Upload to Release
    uses: esphome/workflows/.github/workflows/upload-to-gh-release.yml@2025.1.0
    needs:
      - build-firmware
    with:
      version: ${{ github.event.release.tag_name }}

  upload-to-otaserv:
    name: Upload binary and md5 to ota server
    runs-on: ubuntu-latest
    needs:
      - upload-to-release

    steps:
      - name: Add SSH key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p /home/runner/.ssh
          ssh-keyscan otaserv.mikkel.cc >> /home/runner/.ssh/known_hosts
          echo "${{ secrets.SFTP_KEY }}" > /home/runner/.ssh/github_actions
          chmod 600 /home/runner/.ssh/github_actions
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add /home/runner/.ssh/github_actions

      - name: Download ota bin and md5
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir files
          cd files
          curl -O https://github.com/Duckle29/InKli/releases/latest/download/inkli-esp32.ota.bin
          curl -O https://github.com/Duckle29/InKli/releases/latest/download/inkli-esp32.ota.bin.md5
          scp ./* otaserv@otaserv.mikkel.cc:/inkli/